services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: src/WebApplication1/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    
  identity:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=identityDatabase
    ports:
      - "5432:5432"
